package dev.portfolio.finance.integration;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import java.time.LocalDate;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class FinanceWorkflowIntegrationTest {

    private static final String TEST_EMAIL =
            "integration@example.com";

    private static final String TEST_PASSWORD =
            "Password123!";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JsonMapper jsonMapper;

    @Test
    void shouldCompleteAuthenticatedFinanceWorkflow()
            throws Exception {

        /*
         * Step 1:
         * Register a real user through the HTTP API.
         *
         * This exercises:
         * Controller -> UserService -> UserRepository -> H2
         */
        registerUser(
                "Integration",
                "User",
                TEST_EMAIL,
                TEST_PASSWORD
        );

        /*
         * Step 2:
         * Log in using the newly registered account.
         *
         * A real JWT should be generated by JwtService.
         */
        String authorizationHeader =
                loginAndGetAuthorizationHeader(
                        TEST_EMAIL,
                        TEST_PASSWORD
                );

        /*
         * Step 3:
         * Verify the JWT works against an authenticated
         * endpoint.
         *
         * This goes through the actual Spring Security
         * filter chain and JwtAuthenticationFilter.
         */
        mockMvc.perform(
                        get("/api/auth/me")
                                .header(
                                        "Authorization",
                                        authorizationHeader
                                )
                )
                .andExpect(status().isOk())
                .andExpect(
                        jsonPath("$.email")
                                .value(TEST_EMAIL)
                );

        /*
         * Step 4:
         * Create a user-owned category through the real API.
         */
        String categoryRequest = """
                {
                  "name": "Integration Expenses",
                  "budgetEnabled": true
                }
                """;

        MvcResult categoryResult =
                mockMvc.perform(
                                post("/api/categories")
                                        .header(
                                                "Authorization",
                                                authorizationHeader
                                        )
                                        .contentType(
                                                MediaType.APPLICATION_JSON
                                        )
                                        .content(categoryRequest)
                        )
                        .andExpect(status().isCreated())
                        .andExpect(
                                jsonPath("$.name")
                                        .value("Integration Expenses")
                        )
                        .andExpect(
                                jsonPath("$.budgetEnabled")
                                        .value(true)
                        )
                        .andReturn();

        String categoryResponse =
                categoryResult.getResponse()
                        .getContentAsString();

        JsonNode categoryJson =
                jsonMapper.readTree(categoryResponse);

        long categoryId =
                categoryJson.get("id")
                        .asLong();

        /*
         * Step 5:
         * Create an expense transaction owned by the same
         * authenticated user.
         *
         * LocalDate.now() is used because DashboardService
         * calculates monthly totals using the current month.
         */
        LocalDate transactionDate =
                LocalDate.now();

        String transactionRequest = """
                {
                  "categoryId": %d,
                  "type": "EXPENSE",
                  "amount": 125.50,
                  "description": "Integration test expense",
                  "transactionDate": "%s"
                }
                """.formatted(
                categoryId,
                transactionDate
        );

        mockMvc.perform(
                        post("/api/transactions")
                                .header(
                                        "Authorization",
                                        authorizationHeader
                                )
                                .contentType(
                                        MediaType.APPLICATION_JSON
                                )
                                .content(transactionRequest)
                )
                .andExpect(status().isCreated())
                .andExpect(
                        jsonPath("$.categoryId")
                                .value(categoryId)
                )
                .andExpect(
                        jsonPath("$.type")
                                .value("EXPENSE")
                )
                .andExpect(
                        jsonPath("$.amount")
                                .value(125.50)
                )
                .andExpect(
                        jsonPath("$.description")
                                .value(
                                        "Integration test expense"
                                )
                );

        /*
         * Step 6:
         * Retrieve the dashboard.
         *
         * The transaction created above should now affect:
         *
         * - total expenses
         * - current balance
         * - monthly expenses
         * - recent transactions
         * - category spending
         *
         * This proves the HTTP, security, service,
         * repository, JPA and dashboard aggregation layers
         * work together.
         */
        mockMvc.perform(
                        get("/api/dashboard")
                                .header(
                                        "Authorization",
                                        authorizationHeader
                                )
                )
                .andExpect(status().isOk())
                .andExpect(
                        jsonPath("$.totalIncome")
                                .value(0)
                )
                .andExpect(
                        jsonPath("$.totalExpenses")
                                .value(125.50)
                )
                .andExpect(
                        jsonPath("$.currentBalance")
                                .value(-125.50)
                )
                .andExpect(
                        jsonPath("$.monthlyIncome")
                                .value(0)
                )
                .andExpect(
                        jsonPath("$.monthlyExpenses")
                                .value(125.50)
                )
                .andExpect(
                        jsonPath(
                                "$.recentTransactions.length()"
                        ).value(1)
                )
                .andExpect(
                        jsonPath(
                                "$.recentTransactions[0].description"
                        ).value(
                                "Integration test expense"
                        )
                )
                .andExpect(
                        jsonPath(
                                "$.recentTransactions[0].amount"
                        ).value(125.50)
                )
                .andExpect(
                        jsonPath(
                                "$.recentTransactions[0].type"
                        ).value("EXPENSE")
                )
                .andExpect(
                        jsonPath(
                                "$.categorySpending.length()"
                        ).value(1)
                )
                .andExpect(
                        jsonPath(
                                "$.categorySpending[0].categoryName"
                        ).value(
                                "Integration Expenses"
                        )
                )
                .andExpect(
                        jsonPath(
                                "$.categorySpending[0].amountSpent"
                        ).value(125.50)
                );
    }

    @Test
    void shouldHideAnotherUsersTransaction()
            throws Exception {

        /*
         * Step 1:
         * Register and authenticate User A.
         */
        String ownerEmail =
                "integration-owner@example.com";

        registerUser(
                "Transaction",
                "Owner",
                ownerEmail,
                TEST_PASSWORD
        );

        String ownerAuthorizationHeader =
                loginAndGetAuthorizationHeader(
                        ownerEmail,
                        TEST_PASSWORD
                );

        /*
         * Step 2:
         * User A creates their own category.
         */
        String categoryRequest = """
                {
                  "name": "Private Expenses",
                  "budgetEnabled": true
                }
                """;

        MvcResult categoryResult =
                mockMvc.perform(
                                post("/api/categories")
                                        .header(
                                                "Authorization",
                                                ownerAuthorizationHeader
                                        )
                                        .contentType(
                                                MediaType.APPLICATION_JSON
                                        )
                                        .content(categoryRequest)
                        )
                        .andExpect(status().isCreated())
                        .andReturn();

        JsonNode categoryJson =
                jsonMapper.readTree(
                        categoryResult.getResponse()
                                .getContentAsString()
                );

        long categoryId =
                categoryJson.get("id")
                        .asLong();

        /*
         * Step 3:
         * User A creates a transaction.
         *
         * We capture its ID so User B can attempt to access
         * that exact resource.
         */
        String transactionRequest = """
                {
                  "categoryId": %d,
                  "type": "EXPENSE",
                  "amount": 75.00,
                  "description": "Private owner transaction",
                  "transactionDate": "%s"
                }
                """.formatted(
                categoryId,
                LocalDate.now()
        );

        MvcResult transactionResult =
                mockMvc.perform(
                                post("/api/transactions")
                                        .header(
                                                "Authorization",
                                                ownerAuthorizationHeader
                                        )
                                        .contentType(
                                                MediaType.APPLICATION_JSON
                                        )
                                        .content(transactionRequest)
                        )
                        .andExpect(status().isCreated())
                        .andExpect(
                                jsonPath("$.description")
                                        .value(
                                                "Private owner transaction"
                                        )
                        )
                        .andReturn();

        JsonNode transactionJson =
                jsonMapper.readTree(
                        transactionResult.getResponse()
                                .getContentAsString()
                );

        long transactionId =
                transactionJson.get("id")
                        .asLong();

        /*
         * Step 4:
         * Register and authenticate a completely different
         * user.
         */
        String otherUserEmail =
                "integration-other@example.com";

        registerUser(
                "Other",
                "User",
                otherUserEmail,
                TEST_PASSWORD
        );

        String otherUserAuthorizationHeader =
                loginAndGetAuthorizationHeader(
                        otherUserEmail,
                        TEST_PASSWORD
                );

        /*
         * Step 5:
         * User B attempts to retrieve User A's transaction.
         *
         * The API intentionally returns 404 rather than 403.
         *
         * This prevents the API from revealing whether a
         * resource belonging to another user exists.
         *
         * This exercises:
         *
         * JWT -> Controller -> Service -> ownership-aware
         * Repository query -> exception handling -> HTTP 404
         */
        mockMvc.perform(
                        get(
                                "/api/transactions/{id}",
                                transactionId
                        )
                                .header(
                                        "Authorization",
                                        otherUserAuthorizationHeader
                                )
                )
                .andExpect(status().isNotFound());
    }

    /*
     * Helper used by the integration tests to create users
     * through the real registration endpoint.
     *
     * This is intentionally an HTTP helper rather than
     * inserting users directly through UserRepository.
     * The integration tests should exercise the actual
     * application workflow.
     */
    private void registerUser(
            String firstName,
            String lastName,
            String email,
            String password
    ) throws Exception {

        String registerRequest = """
                {
                  "firstName": "%s",
                  "lastName": "%s",
                  "email": "%s",
                  "password": "%s"
                }
                """.formatted(
                firstName,
                lastName,
                email,
                password
        );

        mockMvc.perform(
                        post("/api/auth/register")
                                .contentType(
                                        MediaType.APPLICATION_JSON
                                )
                                .content(registerRequest)
                )
                .andExpect(status().isCreated())
                .andExpect(
                        jsonPath("$.email")
                                .value(email)
                );
    }

    /*
     * Logs in through the real authentication endpoint,
     * extracts the generated JWT and returns a complete
     * Authorization header.
     */
    private String loginAndGetAuthorizationHeader(
            String email,
            String password
    ) throws Exception {

        String loginRequest = """
                {
                  "email": "%s",
                  "password": "%s"
                }
                """.formatted(
                email,
                password
        );

        MvcResult loginResult =
                mockMvc.perform(
                                post("/api/auth/login")
                                        .contentType(
                                                MediaType.APPLICATION_JSON
                                        )
                                        .content(loginRequest)
                        )
                        .andExpect(status().isOk())
                        .andExpect(
                                jsonPath("$.accessToken")
                                        .isNotEmpty()
                        )
                        .andExpect(
                                jsonPath("$.tokenType")
                                        .value("Bearer")
                        )
                        .andReturn();

        JsonNode loginJson =
                jsonMapper.readTree(
                        loginResult.getResponse()
                                .getContentAsString()
                );

        String accessToken =
                loginJson.get("accessToken")
                        .stringValue();

        return "Bearer " + accessToken;
    }
}