package dev.portfolio.finance.entity;

import static org.assertj.core.api.Assertions.assertThat;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Types;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl;
import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.boot.model.relational.Namespace;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.dialect.Dialect;
import org.hibernate.dialect.MySQLDialect;
import org.hibernate.mapping.Column;
import org.hibernate.mapping.Table;
import org.hibernate.tool.schema.extract.internal.ColumnInformationImpl;
import org.hibernate.tool.schema.extract.spi.ColumnInformation;
import org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Production runs ddl-auto=validate against MySQL, while repository tests use an H2
 * schema generated by Hibernate. Without a MySQL server, this applies Hibernate's own
 * column-type matching rule to the metadata MySQL reports for each V5 column.
 */
class RefreshSessionMySqlMappingTest {

    /** JDBC type code and type name MySQL Connector/J reports for the V5 columns. */
    private static final Map<String, Object[]> V5_MYSQL_COLUMNS = new LinkedHashMap<>();

    static {
        V5_MYSQL_COLUMNS.put("refresh_sessions.id", new Object[] {Types.CHAR, "CHAR"});
        V5_MYSQL_COLUMNS.put("refresh_sessions.user_id", new Object[] {Types.BIGINT, "BIGINT"});
        V5_MYSQL_COLUMNS.put("refresh_sessions.created_at", new Object[] {Types.TIMESTAMP, "DATETIME"});
        V5_MYSQL_COLUMNS.put("refresh_sessions.expires_at", new Object[] {Types.TIMESTAMP, "DATETIME"});
        V5_MYSQL_COLUMNS.put("refresh_sessions.revoked_at", new Object[] {Types.TIMESTAMP, "DATETIME"});
        V5_MYSQL_COLUMNS.put("refresh_sessions.revocation_reason", new Object[] {Types.VARCHAR, "VARCHAR"});
        V5_MYSQL_COLUMNS.put("refresh_tokens.id", new Object[] {Types.BIGINT, "BIGINT"});
        V5_MYSQL_COLUMNS.put("refresh_tokens.session_id", new Object[] {Types.CHAR, "CHAR"});
        V5_MYSQL_COLUMNS.put("refresh_tokens.token_hash", new Object[] {Types.BINARY, "BINARY"});
        V5_MYSQL_COLUMNS.put("refresh_tokens.created_at", new Object[] {Types.TIMESTAMP, "DATETIME"});
        V5_MYSQL_COLUMNS.put("refresh_tokens.consumed_at", new Object[] {Types.TIMESTAMP, "DATETIME"});
    }

    @TempDir
    Path tempDir;

    private StandardServiceRegistry registry;
    private Metadata metadata;

    @BeforeEach
    void buildMysqlMetadata() {
        registry = new StandardServiceRegistryBuilder()
                // No server: declare the product so Hibernate resolves MySQLDialect itself.
                .applySetting("jakarta.persistence.database-product-name", "MySQL")
                .applySetting("jakarta.persistence.database-product-version", "8.0")
                .applySetting("hibernate.boot.allow_jdbc_metadata_access", "false")
                .applySetting("hibernate.physical_naming_strategy",
                        PhysicalNamingStrategySnakeCaseImpl.class.getName())
                .build();
        metadata = new MetadataSources(registry)
                .addAnnotatedClasses(User.class, RefreshSession.class, RefreshToken.class)
                .buildMetadata();
    }

    @AfterEach
    void destroyRegistry() {
        StandardServiceRegistryBuilder.destroy(registry);
    }

    private Map<String, Column> mappedColumns() {
        Map<String, Column> columns = new LinkedHashMap<>();
        for (Namespace namespace : metadata.getDatabase().getNamespaces()) {
            for (Table table : namespace.getTables()) {
                if (table.getName().startsWith("refresh_")) {
                    table.getColumns().forEach(column ->
                            columns.put(table.getName() + "." + column.getName(), column));
                }
            }
        }
        return columns;
    }

    /** Hibernate's package-private rule used by ddl-auto=validate. */
    private boolean validatorAccepts(Column column, int typeCode, String typeName) throws Exception {
        Class<?> definitions = Class.forName("org.hibernate.tool.schema.internal.ColumnDefinitions");
        Method matcher = definitions.getDeclaredMethod("hasMatchingType",
                Column.class, ColumnInformation.class, Metadata.class, Dialect.class);
        matcher.setAccessible(true);
        ColumnInformation info = new ColumnInformationImpl(null, Identifier.toIdentifier(column.getName()),
                typeCode, typeName, 0, 0, column.isNullable());
        return (boolean) matcher.invoke(null, column, info, metadata, new MySQLDialect());
    }

    @Test
    void everyMappedColumnPassesMysqlValidationAgainstV5() throws Exception {
        Map<String, Column> columns = mappedColumns();
        assertThat(columns.keySet()).containsExactlyInAnyOrderElementsOf(V5_MYSQL_COLUMNS.keySet());

        for (var entry : V5_MYSQL_COLUMNS.entrySet()) {
            Column column = columns.get(entry.getKey());
            assertThat(validatorAccepts(column, (int) entry.getValue()[0], (String) entry.getValue()[1]))
                    .as(entry.getKey()).isTrue();
        }
    }

    @Test
    void validationCheckDetectsMismatchedTypes() throws Exception {
        Map<String, Column> columns = mappedColumns();

        // Guards against a vacuous check: incompatible storage must be rejected.
        assertThat(validatorAccepts(columns.get("refresh_tokens.token_hash"), Types.VARCHAR, "VARCHAR"))
                .isFalse();
        assertThat(validatorAccepts(columns.get("refresh_sessions.expires_at"), Types.BIGINT, "BIGINT"))
                .isFalse();
        assertThat(validatorAccepts(columns.get("refresh_sessions.id"), Types.BINARY, "BINARY"))
                .isFalse();
    }

    @Test
    void mappingNullabilityMatchesV5() {
        Map<String, Column> columns = mappedColumns();

        assertThat(columns.entrySet()).allSatisfy(entry -> assertThat(entry.getValue().isNullable())
                .as(entry.getKey())
                .isEqualTo(entry.getKey().endsWith("revoked_at") || entry.getKey().endsWith("revocation_reason")
                        || entry.getKey().endsWith("consumed_at")));
    }

    @Test
    void generatedMysqlDdlUsesUtcDatetimeFixedBinaryAndCascade() throws Exception {
        Path script = tempDir.resolve("mysql.sql");
        SchemaManagementToolCoordinator.process(metadata, registry, Map.of(
                "jakarta.persistence.schema-generation.database.action", "none",
                "jakarta.persistence.schema-generation.scripts.action", "create",
                "jakarta.persistence.schema-generation.scripts.create-target", script.toString(),
                "hibernate.hbm2ddl.delimiter", ";"), action -> { });
        String ddl = Files.readString(script).toLowerCase(Locale.ROOT);

        assertThat(ddl).contains("token_hash binary(32) not null", "created_at datetime(6) not null",
                "expires_at datetime(6) not null", "revocation_reason varchar(24)");
        assertThat(ddl).doesNotContain("varbinary", "timestamp", "enum(");
        assertThat(ddl).containsPattern(
                "alter table refresh_tokens add constraint \\w+ foreign key \\(session_id\\) "
                        + "references refresh_sessions \\(id\\) on delete cascade");
    }
}
