package dev.portfolio.finance.storage;

/**
 * Future provider adapter contract. No implementation is registered in Phase 1.
 * Keys are generated by backend code, never accepted from browser requests.
 */
public interface ProfilePhotoStorage extends ProfilePhotoUrlResolver {
    /** Store validated, processed JPEG bytes at a fresh key without overwriting. */
    void store(String generatedKey, byte[] processedJpeg);

    /** Delete only a backend-owned persisted key; already absent counts as success. */
    void delete(String persistedKey);
}
