package dev.portfolio.finance.storage;

/**
 * Provider adapter contract. Mutations fail explicitly when the feature is disabled.
 * Keys are generated by backend code, never accepted from browser requests.
 */
public interface ProfilePhotoStorage extends ProfilePhotoUrlResolver {
    /** Store only ProfilePhotoProcessor output at a fresh key without overwriting.
     * The byte-array contract is internal: later orchestration must never pass upload bytes directly. */
    void store(String generatedKey, byte[] processedJpeg);

    /** Delete only a backend-owned persisted key; already absent counts as success. */
    void delete(String persistedKey);
}
